### ISSUE TITLE
socket conflicts with w32time of Windows service

### ISSUE THREAD

**Issue by Jamwe** [harp077/pj-ntp-server#1]
java  -jar  pj-ntp-server\pj-ntp-server.jar
java.net.BindException: Address already in use: Cannot bind
        at java.net.DualStackPlainDatagramSocketImpl.socketBind(Native Method)
        at java.net.DualStackPlainDatagramSocketImpl.bind0(DualStackPlainDatagramSocketImpl.java:80)
        at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:94)
        at java.net.DatagramSocket.bind(DatagramSocket.java:392)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:299)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:271)
        at my.harp07.ntp.SimpleNTPServer.connect(SimpleNTPServer.java:83)
        at my.harp07.ntp.SimpleNTPServer.start(SimpleNTPServer.java:100)
        at my.harp07.ntp.SimpleNTPServer.main(SimpleNTPServer.java:196)

Because  w32time of Windows service has already use port 123. Could there be an optimization version to coexist with w32time such as tftpd32 ?

**Comment by harp077** [comment]
Good day Jammie !

That's right - the port is already busy - so this message.You can either stop the w32time time service OR use a different port for pj-ntp-server, for example:

    java -jar pj-ntp-server.jar 1111

 where 1111=udp-port of pj-ntp-server listen.
No other way.

"Because w32time of Windows service has already use port 123. Could there be an optimization version to coexist with w32time such as tftpd32 ?" - NO, tftpd32 use a different port 69 by default, so they can work together.

With best regards and respect,
Roman Koldaev

**Comment by harp077** [comment]
With best regards and respect,
Roman Koldaev

**Comment by Jamwe** [comment]
Hi Koldaev !

Thanks for sharing. It seems that tftpd32 indeed use port 123 via netstat. 

Since the port used by the client in my case cannot be changed, so I forked your project to get it work through multicast. Thanks for your efforts again.
